import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const blanchCaps = localFont({
  src: "fonts/blanch_caps_inline-webfont.woff",
  variable: "--font-1",
  display: "swap",
});

const haymakerWebfont = localFont({
  src: "fonts/haymaker-webfont.woff",
  variable: "--font-2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${blanchCaps.variable} ${haymakerWebfont.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
